# Generated by Django 5.0 on 2023-12-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Описание'),
        ),
    ]
