# Generated by Django 5.0 on 2023-12-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_members', '0002_alter_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='header',
            field=models.TextField(blank=True, max_length=64, verbose_name='Заголовок'),
        ),
    ]
